export function getPfraDom(root = document) {
  const byId = (id) => root.getElementById(id);
  const legacyCardioSelect = byId('cardio-sel');

  return {
    ageSelect: byId('age-sel'),
    altitudeSelect: byId('alt-select'),
    body: root.body,
    bodyScoreText: byId('pfra-body-score'),
    cardioEvent: byId('pfra-cardio-event'),
    cardioLabel: byId('pfra-cardio-label'),
    cardioPerformance: byId('pfra-cardio-performance'),
    cardioScoreText: byId('pfra-cardio-score'),
    coreEvent: byId('pfra-core-event'),
    coreLabel: byId('pfra-core-label'),
    corePerformance: byId('pfra-core-performance'),
    coreScoreText: byId('pfra-core-score'),
    legacyCardioSelect,
    legacyCardioText: byId('run-txt-p'),
    legacyCoreText: byId('sit-txt-p'),
    legacyHamrOption: legacyCardioSelect?.querySelector('option[value="Shuttle Run"]'),
    legacyLapText: byId('run-lap-times'),
    legacyPlankMinuteInput: byId('plankmintxt'),
    legacyPushInput: byId('push-txt'),
    legacyPushSelect: byId('push-sel'),
    legacyPushSlider: byId('push-slider'),
    legacyRunMinuteInput: byId('run-mintxt'),
    legacyRunSecondInput: byId('run-sectxt'),
    legacyRunSlider: byId('run-slider'),
    legacySitInput: byId('sit-txt'),
    legacySitSelect: byId('sit-sel'),
    legacySitSlider: byId('sit-slider'),
    legacyStrengthText: byId('push-txt-p'),
    legacyTwoMileOption: legacyCardioSelect?.querySelector('option[value="1.5 Mile"]'),
    legacyWalkOption: legacyCardioSelect?.querySelector('option[value="Walk"]'),
    pfraResult: byId('pfra-result'),
    pfraStatus: byId('pfra-status'),
    sexSelect: byId('sex-sel'),
    standardsMode: byId('standards-mode'),
    strengthEvent: byId('pfra-strength-event'),
    strengthLabel: byId('pfra-strength-label'),
    strengthPerformance: byId('pfra-strength-performance'),
    strengthScoreText: byId('pfra-strength-score'),
    totalScoreParagraph: byId('score-txt'),
    whtrInput: byId('pfra-whtr'),
  };
}

